//! The routes, and the embedded UI behind them.
//!
//! Everything with behaviour worth arguing about lives in `inspect-model`, so
//! these handlers are deliberately dull: read the current inspection, serialise
//! part of it, return it. The one judgement call here is what a request for a
//! module nobody loaded should say, and the answer is the list of modules that
//! *are* loaded — a 404 whose body names the alternatives is the difference
//! between a dead end and a correction.

use axum::{
    Json, Router,
    extract::{Path, State},
    http::{StatusCode, Uri, header},
    response::{IntoResponse, Response},
    routing::get,
};
use rust_embed::RustEmbed;
use serde::Serialize;
use ts_rs::TS;

use crate::state::{AppState, ModuleSource};

/// Whether an asset's name carries a content hash.
///
/// Vite emits `assets/index-C1TlQqgo.js`: a name that changes whenever the
/// bytes do, which is exactly the condition under which caching forever is
/// safe.
fn is_fingerprinted(path: &str) -> bool {
    path.starts_with("assets/")
}

/// The built UI, baked into the binary.
///
/// `allium-inspect` is one file people copy onto a machine and run; an assets
/// directory it had to find at runtime would be one more thing to get wrong.
///
/// `allow_missing` because the directory is generated by `just ui-build` and is
/// not in the repository. Without it a fresh clone cannot `cargo build` at all,
/// and the error names a derive macro rather than the missing step — so
/// `cargo test`, `cargo clippy` and `just check` all fail for a stranger before
/// they reach anything real. Missing assets are a runtime 404 that says which
/// recipe to run instead, and the route test below is written to hold either
/// way.
#[derive(RustEmbed)]
#[folder = "assets/"]
#[allow_missing = true]
struct Assets;

/// What `/api/health` answers.
#[derive(Serialize, TS)]
#[ts(export, export_to = "../../../ui/src/lib/api/")]
pub struct Health {
    /// Whether the specification is currently in good order.
    ///
    /// False for either of two different problems, which the fields below tell
    /// apart: the reload itself failed, or it succeeded and the spec it read
    /// carries error-severity diagnostics. The second is the common one — a
    /// spec that stops parsing mid-edit still produces a document describing
    /// what is wrong, so the graph rebuilds fine and is simply reporting an
    /// error. Saying `ok` there would be reading the fact that the *tool*
    /// worked as a claim about the *spec*.
    ok: bool,
    /// How many times the answer has changed since the server started.
    ///
    /// The browser polls this and re-fetches when it moves. That is the whole
    /// of the live-reload mechanism, and it is a poll rather than a stream
    /// deliberately: one request a second to a loopback socket costs nothing,
    /// it carries the state of the spec in the same response, and it has no
    /// connection to lose, reconnect, or leave half-open behind a laptop lid.
    #[ts(type = "number")]
    revision: u64,
    allium_version: String,
    modules: Vec<String>,
    /// Why the last reload failed, when it did.
    error: Option<String>,
    /// How many error-severity diagnostics the current spec carries.
    errors: usize,
    warnings: usize,
}

/// The router, with `state` behind every API route.
pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/api/health", get(health))
        .route("/api/spec", get(spec))
        .route("/api/spec/source/{module}", get(source))
        .route("/api/journeys", get(journeys))
        .route("/api/evidence/{image}", get(evidence))
        .route("/api/sim/setup", get(crate::sim::setup))
        .route("/api/sim/step", axum::routing::post(crate::sim::take_step))
        .fallback(assets)
        .with_state(state)
}

/// Serve until the process is stopped.
///
/// Here rather than in the binary so `axum` stays one crate's concern. The
/// binary decides *which* port; how to answer on it is this crate's business.
///
/// # Errors
///
/// Returns whatever the server stopped with.
pub async fn serve(listener: tokio::net::TcpListener, state: AppState) -> std::io::Result<()> {
    axum::serve(listener, router(state)).await
}

async fn health(State(state): State<AppState>) -> Json<Health> {
    let inspection = state.get();
    let count =
        |severity| inspection.graph.diagnostics.iter().filter(|d| d.severity == severity).count();
    let errors = count(inspect_model::Severity::Error);
    Json(Health {
        ok: state.error().is_none() && errors == 0,
        revision: state.revision(),
        allium_version: inspection.graph.allium_version.clone(),
        modules: inspection.modules().map(ToOwned::to_owned).collect(),
        error: state.error(),
        errors,
        warnings: count(inspect_model::Severity::Warning),
    })
}

async fn spec(State(state): State<AppState>) -> Json<inspect_model::SpecGraph> {
    Json(state.get().graph.clone())
}

/// Every authored journey, walked against the spec as it stands now.
///
/// Recomputed with the inspection on each reload, so this is always a report
/// about the graph the rest of the browser is showing.
async fn journeys(State(state): State<AppState>) -> Json<crate::JourneyReport> {
    Json(state.get().journeys().clone())
}

/// One picture a sealed frame names.
///
/// The manifest is the allowlist: the name is looked up among the frames, and
/// nothing a client sends is ever joined to a path. A sanitiser would have to
/// be right about every spelling of `..`; a lookup has to be right about
/// nothing. See `evidence::Evidence::picture`.
async fn evidence(
    State(state): State<AppState>,
    Path(image): Path<String>,
) -> Result<Response, Response> {
    let inspection = state.get();
    let Some(path) = inspection.evidence().picture(&image) else {
        return Err(
            (StatusCode::NOT_FOUND, format!("no sealed frame names `{image}`")).into_response()
        );
    };

    let bytes = std::fs::read(&path).map_err(|error| {
        (StatusCode::NOT_FOUND, format!("`{image}` could not be read: {error}")).into_response()
    })?;

    // Named by the run that took it and served from a directory that changes
    // under us, so it is revalidated rather than cached: a walk re-run between
    // two reloads would otherwise show the previous run's pictures.
    Ok(([(header::CONTENT_TYPE, picture_type(&image)), (header::CACHE_CONTROL, "no-cache")], bytes)
        .into_response())
}

/// What kind of picture a name says it is.
///
/// A short list rather than a crate: a harness photographs a screen, and this
/// is what a screenshot is saved as. Anything else is served as bytes the
/// browser is left to sniff, which for an `<img>` means it simply will not
/// render — the honest outcome for a file nothing here claims to understand.
fn picture_type(image: &str) -> &'static str {
    match image.rsplit_once('.').map(|(_, extension)| extension.to_ascii_lowercase()) {
        Some(extension) if extension == "png" => "image/png",
        Some(extension) if extension == "jpg" || extension == "jpeg" => "image/jpeg",
        Some(extension) if extension == "webp" => "image/webp",
        Some(extension) if extension == "avif" => "image/avif",
        _ => "application/octet-stream",
    }
}

async fn source(
    State(state): State<AppState>,
    Path(module): Path<String>,
) -> Result<Json<ModuleSource>, Response> {
    let inspection = state.get();
    match inspection.source(&module) {
        Some(source) => Ok(Json(source.clone())),
        None => {
            // Two different answers. A module the graph does not have is a
            // wrong name, and the list of right ones is the correction. A
            // module the graph *does* have, whose file could not be re-read,
            // is a missing file — and telling that reader "no module named
            // `lending` is loaded" denies something they can see on the canvas
            // in front of them.
            let in_graph = inspection.graph.modules.iter().any(|declared| declared.name == module);
            let body = if in_graph {
                format!(
                    "`{module}` is in the graph, but its file could not be read back. It was                      readable when the spec was ingested, so it has most likely been moved,                      renamed or deleted since."
                )
            } else {
                let known: Vec<&str> = inspection.modules().collect();
                format!(
                    "no module named `{module}` is loaded. Loaded modules: {}",
                    if known.is_empty() { "none".to_owned() } else { known.join(", ") }
                )
            };
            Err((StatusCode::NOT_FOUND, body).into_response())
        }
    }
}

/// Serve the embedded UI, falling back to `index.html`.
///
/// The fallback is what makes a link to a construct work: the UI keeps the
/// selection in the path, so a reload of `/entity/Book` has to reach the app
/// rather than 404 on a file that was never going to exist.
async fn assets(uri: Uri) -> Response {
    let path = uri.path().trim_start_matches('/');
    let path = if path.is_empty() { "index.html" } else { path };

    match Assets::get(path).or_else(|| Assets::get("index.html")) {
        Some(file) => {
            let mime = file.metadata.mimetype();
            // Vite fingerprints every asset it emits, so those may be cached
            // forever — the name changes when the contents do. `index.html` is
            // the one file with a stable name, so it must never be cached: it
            // is what names the current bundle, and a stale copy of it pins the
            // browser to a build that is no longer on disk. That is not a
            // theoretical concern here, where rebuilding the UI while the tool
            // is open is the normal way to work on it.
            let caching = if is_fingerprinted(path) {
                "public, max-age=31536000, immutable"
            } else {
                "no-cache"
            };
            ([(header::CONTENT_TYPE, mime), (header::CACHE_CONTROL, caching)], file.data)
                .into_response()
        }
        None => (
            StatusCode::NOT_FOUND,
            "The UI was not built into this binary. Run `just build`, which runs \
             `just ui-build` first.",
        )
            .into_response(),
    }
}

#[cfg(test)]
mod tests {
    use axum::body::{Body, to_bytes};
    use http::Request;
    use serde_json::Value;
    use tower::ServiceExt;

    use super::*;
    use crate::{JourneyReport, state::Inspection};

    /// A server over the two fixture modules, with no socket involved.
    fn server() -> Router {
        router(AppState::new(fixture_inspection()))
    }

    fn fixture_inspection() -> Inspection {
        Inspection::from_parts(
            inspect_model::SpecGraph::new("allium 3.5.3"),
            vec![ModuleSource {
                module: "catalogue".to_owned(),
                path: "specs/catalogue.allium".to_owned(),
                text: "entity Book {}\n".to_owned(),
            }],
        )
    }

    async fn get(app: Router, uri: &str) -> (StatusCode, String) {
        let response = app
            .oneshot(Request::builder().uri(uri).body(Body::empty()).expect("a request"))
            .await
            .expect("a response");
        let status = response.status();
        let bytes = to_bytes(response.into_body(), 1 << 20).await.expect("a body");
        (status, String::from_utf8_lossy(&bytes).into_owned())
    }

    #[tokio::test]
    async fn health_reports_the_cli_and_the_modules() {
        let (status, body) = get(server(), "/api/health").await;
        assert_eq!(status, StatusCode::OK);
        let json: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(json["ok"], true);
        assert_eq!(json["allium_version"], "allium 3.5.3");
        assert_eq!(json["modules"][0], "catalogue");
        assert_eq!(json["error"], Value::Null);
    }

    #[tokio::test]
    async fn health_is_not_ok_when_the_spec_itself_carries_an_error() {
        // The common case, and the one worth getting right: a spec that stops
        // parsing mid-edit still produces a document describing what is wrong,
        // so the reload succeeds and the graph rebuilds. Reporting `ok` there
        // would read "the tool worked" as "the spec is fine".
        let mut graph = inspect_model::SpecGraph::new("v");
        graph.diagnostics.push(inspect_model::Diagnostic {
            severity: inspect_model::Severity::Error,
            message: "expected '{'".to_owned(),
            code: None,
            location: None,
            module: "catalogue".to_owned(),
            node: None,
        });
        graph.diagnostics.push(inspect_model::Diagnostic {
            severity: inspect_model::Severity::Warning,
            message: "a state is never assigned".to_owned(),
            code: None,
            location: None,
            module: "catalogue".to_owned(),
            node: None,
        });

        let state = AppState::new(Inspection::from_parts(graph, Vec::new()));
        let (_, body) = get(router(state), "/api/health").await;
        let json: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(json["ok"], false);
        assert_eq!(json["errors"], 1);
        assert_eq!(json["warnings"], 1);
        assert_eq!(json["error"], Value::Null, "the reload itself was fine");
    }

    #[tokio::test]
    async fn health_counts_warnings_without_calling_the_spec_unwell() {
        // Warnings are the normal state of a spec under development; a tool
        // that flagged them as failure would cry wolf constantly.
        let mut graph = inspect_model::SpecGraph::new("v");
        graph.diagnostics.push(inspect_model::Diagnostic {
            severity: inspect_model::Severity::Warning,
            message: "unused".to_owned(),
            code: None,
            location: None,
            module: "m".to_owned(),
            node: None,
        });
        let state = AppState::new(Inspection::from_parts(graph, Vec::new()));
        let (_, body) = get(router(state), "/api/health").await;
        let json: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(json["ok"], true);
        assert_eq!(json["warnings"], 1);
    }

    #[tokio::test]
    async fn the_revision_moves_when_the_spec_is_re_read() {
        // The browser has no other way to find out. It fetched a graph once,
        // and a watcher that reloads the server's copy without telling anyone
        // leaves a reader studying a picture of a file that no longer says that.
        let state = AppState::new(fixture_inspection());
        let (_, before) = get(router(state.clone()), "/api/health").await;
        let before: Value = serde_json::from_str(&before).expect("JSON");

        state.replace(fixture_inspection());

        let (_, after) = get(router(state), "/api/health").await;
        let after: Value = serde_json::from_str(&after).expect("JSON");
        assert_eq!(
            after["revision"].as_u64().expect("a number"),
            before["revision"].as_u64().expect("a number") + 1
        );
    }

    #[tokio::test]
    async fn the_revision_moves_when_a_reload_starts_failing() {
        // The graph did not change, but what the reader needs to be told about
        // it did — and they find that out by noticing the number move.
        let state = AppState::new(fixture_inspection());
        let (_, before) = get(router(state.clone()), "/api/health").await;
        let before: Value = serde_json::from_str(&before).expect("JSON");

        state.set_error(Some("expected '{'".to_owned()));

        let (_, after) = get(router(state), "/api/health").await;
        let after: Value = serde_json::from_str(&after).expect("JSON");
        assert!(
            after["revision"].as_u64().expect("a number")
                > before["revision"].as_u64().expect("a number")
        );
    }

    #[tokio::test]
    async fn the_revision_holds_still_when_nothing_happened() {
        // Otherwise every poll looks like a change and the browser refetches
        // the graph once a second forever.
        let state = AppState::new(fixture_inspection());
        state.set_error(None);
        let (_, first) = get(router(state.clone()), "/api/health").await;
        let (_, second) = get(router(state), "/api/health").await;
        let first: Value = serde_json::from_str(&first).expect("JSON");
        let second: Value = serde_json::from_str(&second).expect("JSON");
        assert_eq!(first["revision"], second["revision"]);
    }

    #[tokio::test]
    async fn health_reports_a_failed_reload_rather_than_claiming_to_be_well() {
        // The graph on screen is from before the edit; saying `ok` would let a
        // reader trust a picture the current file no longer produces.
        let state = AppState::new(fixture_inspection());
        state.set_error(Some("expected '{', found 'external'".to_owned()));
        let (_, body) = get(router(state), "/api/health").await;
        let json: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(json["ok"], false);
        assert!(json["error"].as_str().expect("a message").contains("expected"));
    }

    #[tokio::test]
    async fn the_spec_route_returns_the_graph() {
        let (status, body) = get(server(), "/api/spec").await;
        assert_eq!(status, StatusCode::OK);
        let json: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(json["allium_version"], "allium 3.5.3");
        assert!(json["nodes"].is_array());
    }

    #[tokio::test]
    async fn a_modules_source_is_served_with_its_path() {
        let (status, body) = get(server(), "/api/spec/source/catalogue").await;
        assert_eq!(status, StatusCode::OK);
        let json: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(json["module"], "catalogue");
        assert_eq!(json["path"], "specs/catalogue.allium");
        assert_eq!(json["text"], "entity Book {}\n");
    }

    #[tokio::test]
    async fn an_unknown_module_is_told_which_ones_are_loaded() {
        // A 404 whose body names the alternatives is the difference between a
        // dead end and a correction.
        let (status, body) = get(server(), "/api/spec/source/nonesuch").await;
        assert_eq!(status, StatusCode::NOT_FOUND);
        assert!(body.contains("nonesuch"), "{body}");
        assert!(body.contains("catalogue"), "the loaded modules are named: {body}");
    }

    #[tokio::test]
    async fn a_module_whose_file_vanished_is_not_denied_by_the_source_route() {
        // The graph is built once and the files are read back per request, so a
        // module can be on the canvas with no readable file behind it. Telling
        // that reader "no module named `lending` is loaded" denies something
        // they can see in front of them, and sends them looking for a typo in a
        // name that is correct.
        let mut graph = inspect_model::SpecGraph::new("allium 3.5.3");
        graph.modules.push(inspect_model::graph::Module {
            name: "lending".to_owned(),
            path: "specs/lending.allium".to_owned(),
            imports: Vec::new(),
            language_version: None,
        });
        // ... and no `ModuleSource` for it, which is what an unreadable file
        // leaves behind.
        let state = AppState::new(Inspection::from_parts(graph, Vec::new()));

        let (status, body) = get(router(state), "/api/spec/source/lending").await;
        assert_eq!(status, StatusCode::NOT_FOUND);
        assert!(body.contains("in the graph"), "the answer is about the file: {body}");
        assert!(
            !body.contains("no module named"),
            "and not about the name, which is right: {body}"
        );
    }

    #[tokio::test]
    async fn a_module_name_needing_escaping_is_still_found() {
        let state = AppState::new(Inspection::from_parts(
            inspect_model::SpecGraph::new("v"),
            vec![ModuleSource {
                module: "odd name".to_owned(),
                path: "odd name.allium".to_owned(),
                text: String::new(),
            }],
        ));
        let (status, _) = get(router(state), "/api/spec/source/odd%20name").await;
        assert_eq!(status, StatusCode::OK);
    }

    #[tokio::test]
    async fn the_journeys_route_is_served_even_with_none_loaded() {
        // A server started without `--journeys` must still answer, or the view
        // reports itself broken when the truth is that nobody asked for any.
        let (status, body) = get(server(), "/api/journeys").await;
        assert_eq!(status, StatusCode::OK);
        let document: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(document["total"], 0);
        assert_eq!(document["holding"], 0);
        assert_eq!(document["files"].as_array().expect("an array").len(), 0);
    }

    #[tokio::test]
    async fn the_journeys_route_returns_what_was_walked() {
        let report = JourneyReport {
            files: vec![crate::JourneyFile {
                path: "journeys/lending.journey".to_owned(),
                name: "lending.journey".to_owned(),
                error: None,
                text: String::new(),
                walks: Vec::new(),
            }],
            holding: 0,
            total: 0,
            evidence: inspect_journey::resolve(&std::collections::BTreeMap::new(), None, &[]),
        };
        let state = AppState::new(fixture_inspection().with_journeys(report));
        let (status, body) = get(router(state), "/api/journeys").await;
        assert_eq!(status, StatusCode::OK);
        let document: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(document["files"][0]["name"], "lending.journey");
        assert_eq!(document["files"][0]["path"], "journeys/lending.journey");
    }

    /// The traversal defence, asserted at the route rather than only at the
    /// lookup behind it. A server started with no evidence at all has an empty
    /// allowlist, so every name is refused — which is the state most people run
    /// the tool in and the one a regression would slip through.
    #[tokio::test]
    async fn a_picture_no_frame_names_is_not_served() {
        for name in
            ["01.png", "..%2F..%2F..%2Fetc%2Fpasswd", "%2Fetc%2Fpasswd", "%2E%2E%2Fsecret.txt"]
        {
            let state = AppState::new(fixture_inspection());
            let (status, body) = get(router(state), &format!("/api/evidence/{name}")).await;
            assert_eq!(status, StatusCode::NOT_FOUND, "`{name}` was served");
            assert!(body.contains("no sealed frame names"), "`{name}`: {body}");
        }
    }

    #[test]
    fn a_picture_is_served_as_what_its_name_says_it_is() {
        assert_eq!(picture_type("01-a-step.png"), "image/png");
        assert_eq!(picture_type("01.JPEG"), "image/jpeg");
        assert_eq!(picture_type("01.webp"), "image/webp");
        assert_eq!(picture_type("01.avif"), "image/avif");
        // Nothing here claims to know what these are, and saying so leaves an
        // `<img>` refusing to render rather than the browser guessing.
        assert_eq!(picture_type("notes.txt"), "application/octet-stream");
        assert_eq!(picture_type("nodot"), "application/octet-stream");
    }

    #[tokio::test]
    async fn a_state_swap_is_visible_to_the_next_request() {
        let state = AppState::new(fixture_inspection());
        let app = router(state.clone());
        state.replace(Inspection::from_parts(
            inspect_model::SpecGraph::new("allium 4.0.0"),
            Vec::new(),
        ));
        let (_, body) = get(app, "/api/spec").await;
        let json: Value = serde_json::from_str(&body).expect("JSON");
        assert_eq!(json["allium_version"], "allium 4.0.0");
    }

    #[tokio::test]
    async fn replacing_the_inspection_clears_a_previous_failure() {
        let state = AppState::new(fixture_inspection());
        state.set_error(Some("broken".to_owned()));
        state.replace(fixture_inspection());
        assert_eq!(state.error(), None);
    }

    #[test]
    fn only_fingerprinted_assets_may_be_cached_forever() {
        // `index.html` is the one file with a stable name, and it is what names
        // the current bundle. Caching it pins the browser to a build that is no
        // longer on disk — which is what happens every time the UI is rebuilt
        // while the tool is open.
        assert!(is_fingerprinted("assets/index-C1TlQqgo.js"));
        assert!(is_fingerprinted("assets/index-BTEsh_lV.css"));
        assert!(!is_fingerprinted("index.html"));
        assert!(!is_fingerprinted(""));
    }

    /// A request, returning the status, the body, and one header.
    async fn get_with_header(app: Router, uri: &str, header: &str) -> (StatusCode, String, String) {
        let response = app
            .oneshot(Request::builder().uri(uri).body(Body::empty()).expect("a request"))
            .await
            .expect("a response");
        let status = response.status();
        let value = response
            .headers()
            .get(header)
            .and_then(|value| value.to_str().ok())
            .unwrap_or_default()
            .to_owned();
        let bytes = to_bytes(response.into_body(), 1 << 20).await.expect("a body");
        (status, String::from_utf8_lossy(&bytes).into_owned(), value)
    }

    #[tokio::test]
    async fn the_ui_is_either_served_uncached_or_says_how_to_build_it() {
        // Written to hold in both states on purpose. The assets are embedded at
        // compile time, so whether they exist depends on whether `just
        // ui-build` ran before `cargo build` — and a test that only passes in
        // one of those states fails for a reason that has nothing to do with
        // the behaviour it is describing.
        let (status, body, caching) = get_with_header(server(), "/", "cache-control").await;
        if status == StatusCode::NOT_FOUND {
            assert!(body.contains("just build"), "the message names the fix: {body}");
        } else {
            assert_eq!(status, StatusCode::OK);
            assert_eq!(
                caching, "no-cache",
                "index.html names the current bundle, so caching it pins the browser to an old one"
            );
        }
    }

    #[tokio::test]
    async fn an_unknown_path_falls_through_to_the_app() {
        // The UI keeps the selection in the path, so reloading a link to a
        // construct has to reach the app rather than 404 on a file that was
        // never going to exist.
        let (status, _, _) = get_with_header(server(), "/entity/Book", "cache-control").await;
        let (root, _, _) = get_with_header(server(), "/", "cache-control").await;
        assert_eq!(status, root, "a deep link is served exactly as the root is");
    }
}
