#!/usr/bin/env node
// The notice the shipped bundle has to carry.
//
// `cargo deny` covers the Rust half and stops at the crate graph. The binary
// also embeds the built Svelte bundle, which is npm code that no Rust tool ever
// sees — and Vite strips every legal comment on the way, so the licences that
// require their notice to travel with the object code were travelling with
// nothing. ISC, BSD-3-Clause and MIT all require the copyright notice to be
// reproduced in a binary distribution; EPL-2.0 §3.2 requires recipients to be
// told the licence and be able to get the source.
//
// Output goes to `ui/public/`, which Vite copies into the embedded assets, so
// the running tool serves it at `/THIRD-PARTY.txt` and a copy of the binary
// carries its own notices.
//
// Deterministic on purpose: sorted by package name, no timestamps. A generated
// file that changes when nothing changed cannot be a gate.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ui = join(here, "..", "ui");
// Overridable so `gates-selftest.sh` can drive this gate in both directions
// without editing the tree it is checking. Same shape as the file-size gate.
const out = process.env.INSPECT_THIRD_PARTY_OUT || join(ui, "public", "THIRD-PARTY.txt");

/** Licences a shipped frontend dependency may carry. */
const ALLOWED = new Set(
  process.env.INSPECT_THIRD_PARTY_ALLOW
    ? process.env.INSPECT_THIRD_PARTY_ALLOW.split(",").filter(Boolean)
    : [
  "MIT",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "0BSD",
  "CC0-1.0",
  // elkjs, taken under the EPL arm of its dual licence. See the header below.
  "EPL-2.0 OR GPL-3.0-or-later",
      ],
);

/** Where to send somebody who wants the source, per EPL-2.0 §3.2. */
const SOURCE = { elkjs: "https://github.com/kieler/elkjs" };

const LICENCE_FILES = [
  "LICENSE",
  "LICENSE.md",
  "LICENSE.txt",
  "LICENCE",
  "LICENCE.md",
  "LICENSE-MIT",
  "license",
];

function productionPackages() {
  const listed = execFileSync("npm", ["ls", "--omit=dev", "--all", "--parseable"], {
    cwd: ui,
    encoding: "utf8",
  });
  const packages = [];
  for (const dir of listed.split("\n").slice(1)) {
    if (!dir.trim()) continue;
    const manifest = join(dir, "package.json");
    if (!existsSync(manifest)) continue;
    const meta = JSON.parse(readFileSync(manifest, "utf8"));
    packages.push({ dir, name: meta.name, version: meta.version, licence: licenceOf(meta) });
  }
  // Sorted and deduplicated: npm lists a package once per place it is required.
  const seen = new Map();
  for (const one of packages) seen.set(`${one.name}@${one.version}`, one);
  return [...seen.values()].sort((a, b) =>
    a.name === b.name ? a.version.localeCompare(b.version) : a.name.localeCompare(b.name),
  );
}

function licenceOf(meta) {
  if (typeof meta.license === "string") return meta.license;
  if (meta.license?.type) return meta.license.type;
  if (Array.isArray(meta.licenses)) return meta.licenses.map((one) => one.type).join(" OR ");
  return "UNKNOWN";
}

function licenceText(dir) {
  for (const name of LICENCE_FILES) {
    const path = join(dir, name);
    if (existsSync(path)) return readFileSync(path, "utf8").trimEnd();
  }
  return null;
}

const packages = productionPackages();

const unallowed = packages.filter((one) => !ALLOWED.has(one.licence));
if (unallowed.length > 0) {
  console.error("ERROR: a shipped frontend dependency carries an unreviewed licence:");
  for (const one of unallowed) console.error(`  ${one.name}@${one.version} — ${one.licence}`);
  console.error("");
  console.error("       Add it to ALLOWED in scripts/third-party.mjs if it is acceptable,");
  console.error("       or drop the dependency. Copyleft that reaches the bundle is not.");
  process.exit(1);
}

const lines = [];
lines.push("Third-party software in allium-inspect");
lines.push("======================================");
lines.push("");
lines.push("`allium-inspect` is a single binary with its browser interface built in.");
lines.push("That bundle contains the packages below, and their licences travel with it.");
lines.push("");
lines.push("This file is generated by `just third-party` from the production npm tree.");
lines.push("The Rust side is covered separately by `cargo deny check licenses`; see NOTICE");
lines.push("for the crate that matters there.");
lines.push("");
lines.push("elkjs is offered under `EPL-2.0 OR GPL-3.0-or-later`. This project takes it");
lines.push("under the **Eclipse Public License 2.0**. Its source is at");
lines.push(`${SOURCE.elkjs}, as EPL-2.0 section 3.2 requires.`);
lines.push("");
lines.push(`${packages.length} packages.`);
lines.push("");

for (const one of packages) {
  lines.push("-".repeat(76));
  lines.push(`${one.name} ${one.version}`);
  lines.push(one.licence);
  if (SOURCE[one.name]) lines.push(`Source: ${SOURCE[one.name]}`);
  lines.push("");
  const text = licenceText(one.dir);
  lines.push(text ?? `(No licence file shipped in the package. Declared: ${one.licence}.)`);
  lines.push("");
}

const rendered = `${lines.join("\n").trimEnd()}\n`;

if (process.argv.includes("--check")) {
  const existing = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (existing !== rendered) {
    console.error("ERROR: ui/public/THIRD-PARTY.txt is stale.");
    console.error("       Run 'just third-party' and commit the result.");
    console.error("       The bundle ships these licences; a stale notice ships the wrong ones.");
    process.exit(1);
  }
  console.log(`third-party: ${packages.length} packages, notice current`);
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, rendered);
  console.log(`third-party: wrote ${out} (${packages.length} packages)`);
}
