// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An actor: who is on the other side of a surface.
 */
export type ActorDetail = { 
/**
 * The entity type the actor is an instance of.
 */
entity: string | null, 
/**
 * The condition that identifies them, as written.
 */
condition: string | null, 
/**
 * The context type the actor requires from a surface.
 */
within: string | null, };
