// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Value } from "./Value";

/**
 * What somebody said a call comes back as.
 *
 * Matched on argument *values* rather than on the text: a rule writes
 * `may_invite(group, issuer)` where a journey writes `may_invite(chat, she)`,
 * and those are the same call about the same two things.
 */
export type Answer = { call: string, arguments: Array<Value>, value: Value, };
