// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";

/**
 * Somebody or something the journey named, and what it resolved to.
 */
export type CastMember = { 
/**
 * What the journey calls them: `ada`, `loan`.
 */
name: string, 
/**
 * As written, so `catalogue/Copy` keeps its module.
 */
type_expr: string, 
/**
 * The instance in the world, once there was one.
 *
 * `None` when a step that was supposed to create it did not — which is
 * the whole reason this is an option rather than a string.
 */
entity: string | null, origin: Origin, line: number, };
