// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepId } from "./StepId";

/**
 * One place in the code that says it demonstrates a step.
 */
export type Claim = { step: StepId, 
/**
 * The file, as the caller named it — a path a reader can act on.
 */
file: string, line: number, };
