// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Truth } from "./Truth";
import type { Unresolved } from "./Unresolved";

/**
 * One precondition, and what the simulator made of it.
 */
export type ClauseVerdict = { 
/**
 * The clause as the spec wrote it.
 */
text: string, truth: Truth, 
/**
 * What could not be decided, when anything could not.
 */
unresolved: Array<Unresolved>, };
