// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One configuration parameter and its default.
 */
export type ConfigParameter = { name: string, type_expr: string, 
/**
 * The default as written: `21.days`, `20`, `false`.
 */
default_expr: string | null, };
