// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigParameter } from "./ConfigParameter";

/**
 * A module's configuration block.
 */
export type ConfigDetail = { parameters: Array<ConfigParameter>, };
