// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One way a journey says it should be shown, on the wire.
 */
export type Declared = { key: string, 
/**
 * In the order the author wrote them: they chose which question a reader
 * meets first, and sorting would take that away.
 */
values: Array<string>, 
/**
 * The values no picture of this journey carries yet.
 *
 * A declaration is a demand, so this is the backlog for it — the same
 * shape as a step the spec does not support, one level down.
 */
missing: Array<string>, line: number, };
