// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";
import type { Severity } from "./Severity";

/**
 * One structural report about a spec file.
 */
export type Diagnostic = { severity: Severity, message: string, 
/**
 * The CLI's dotted code, such as `allium.status.noExit`. Absent for
 * parse errors, which carry only prose.
 */
code: string | null, 
/**
 * Absent when the CLI reported no location.
 */
location: Location | null, 
/**
 * The module this was reported against, filled in during ingestion.
 */
module: string, 
/**
 * The construct whose declaration encloses this diagnostic, when one does.
 *
 * Attribution happens here rather than in the browser because it needs the
 * spec text and the byte spans together, and the UI has neither until it
 * has fetched a file the reader may never open.
 *
 * It is `None` for a diagnostic no declaration encloses — a parse error is
 * reported where the parser gave up, which is often past the end of the
 * construct that was actually wrong, and guessing a nearby node would put
 * a badge on the wrong box.
 */
node: string | null, };
