// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";
import type { Severity } from "./Severity";

/**
 * One structural report about a spec file.
 */
export type Diagnostic = { severity: Severity, message: string, 
/**
 * The CLI's dotted code, such as `allium.status.noExit`. Absent for
 * parse errors, which carry only prose.
 */
code: string | null, 
/**
 * Absent when the CLI reported no location.
 */
location: Location | null, 
/**
 * The module this was reported against, filled in during ingestion.
 */
module: string, };
