// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a rule responded to the trigger.
 */
export type Disposition = "fired" | "refused" | "undecided" | "unsimulatable";
