// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What relationship an edge stands for.
 */
export type EdgeKind = "field" | "relationship" | "triggers" | "creates" | "mutates" | "emits" | "reads" | "exposes" | "provides" | "facing" | "identified_by" | "constrains" | "imports";
