// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeKind } from "./EdgeKind";
import type { NodeId } from "./NodeId";
import type { Span } from "./Span";

/**
 * A directed relationship between two nodes.
 */
export type Edge = { from: NodeId, to: NodeId, kind: EdgeKind, 
/**
 * What to write on the edge: a field name, a state, an operation.
 */
label: string, 
/**
 * Where the relationship is declared, when known.
 */
span: Span | null, };
