// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { Value } from "./Value";

/**
 * Something a rule did, or refused to do.
 */
export type Effect = { "kind": "created", id: EntityId, entity: string, } | { "kind": "assigned", id: EntityId, field: string, from: Value, to: Value, } | { "kind": "emitted", trigger: string, module: string, arguments: { [key in string]: Value }, } | { "kind": "refused", id: EntityId, field: string, from: string, to: string, reason: string, } | { "kind": "noted", description: string, };
