// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerSource } from "./TriggerSource";
import type { Unresolved } from "./Unresolved";
import type { Value } from "./Value";

/**
 * A state-condition rule that holds now.
 */
export type Enabled = { rule: string, name: string, module: string, 
/**
 * The trigger to fire to run it.
 */
trigger: string, source: TriggerSource, 
/**
 * The instances it holds for, so the user can pick one.
 */
over: Array<Value>, 
/**
 * What the `when` clause calls the instance — the `copy` in
 * `when: copy: Copy.status = lost`. Anything running the rule has to bind
 * it under that name or every clause that mentions it reads as unknown.
 */
binding: string, 
/**
 * Instances whose condition could not be settled, and why.
 *
 * `over` holds the ones this rule definitely holds for. Everything else
 * used to be dropped without distinction, so an instance the condition
 * said *no* about and one nothing could decide left the same trace: none.
 * This was the only verdict-bearing type in a step outcome with nowhere
 * to put a reason, which made it the one place the simulator could go
 * quiet without breaking its own rule.
 */
undecided: Array<Unresolved>, };
