// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerSource } from "./TriggerSource";
import type { Value } from "./Value";

/**
 * A state-condition rule that holds now.
 */
export type Enabled = { rule: string, name: string, module: string, 
/**
 * The trigger to fire to run it.
 */
trigger: string, source: TriggerSource, 
/**
 * The instances it holds for, so the user can pick one.
 */
over: Array<Value>, };
