// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerSource } from "./TriggerSource";
import type { Value } from "./Value";

/**
 * A state-condition rule that holds now.
 */
export type Enabled = { rule: string, name: string, module: string, 
/**
 * The trigger to fire to run it.
 */
trigger: string, source: TriggerSource, 
/**
 * The instances it holds for, so the user can pick one.
 */
over: Array<Value>, 
/**
 * What the `when` clause calls the instance — the `copy` in
 * `when: copy: Copy.status = lost`. Anything running the rule has to bind
 * it under that name or every clause that mentions it reads as unknown.
 */
binding: string, };
