// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The identity of one entity instance in a world.
 *
 * Human-readable on purpose: `Message#1` is what appears in the trace, in the
 * world editor and in a shared link, and an opaque id would make all three
 * harder to read for no gain.
 */
export type EntityId = string;
