// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityField } from "./EntityField";
import type { EntityKind } from "./EntityKind";
import type { TransitionGraph } from "./TransitionGraph";

/**
 * An entity, value type or variant.
 */
export type EntityDetail = { kind: EntityKind, fields: Array<EntityField>, transitions: Array<TransitionGraph>, 
/**
 * The sum type this is a variant of, when it is one.
 */
parent: string | null, };
