// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One field, projection or derived value on an entity.
 */
export type EntityField = { name: string, 
/**
 * The type as written: `Set<Book>`, `catalogue/Copy`, `copies.count`.
 */
type_expr: string, 
/**
 * The states, when the field is an inline enumeration.
 */
enum_values: Array<string>, 
/**
 * Whether the field is computed rather than stored.
 */
derived: boolean, 
/**
 * Whether the field navigates to related entities.
 */
relationship: boolean, 
/**
 * The states this field is only meaningful in, from a `when` qualifier.
 */
when: string | null, };
