// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Value } from "./Value";

/**
 * Something that happens: a trigger, with the arguments it carries.
 */
export type Event = { 
/**
 * The trigger's name, as the spec spells it.
 */
trigger: string, 
/**
 * Where the trigger is declared.
 *
 * A label, not a filter: rules are matched on the trigger's name alone,
 * because a module that `use`s another reacts to triggers that module
 * declares. Narrowing to this module would silence exactly those rules.
 */
module: string, 
/**
 * Argument bindings, by parameter name.
 */
arguments: { [key in string]: Value }, };
