// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One system-level observation from `allium analyse`.
 *
 * The `detail` field keeps the finding's whole original JSON. Finding types
 * differ from one another in shape — a deadlock names a state and its outbound
 * edges, a conflict names two rules and the values they disagree on — and new
 * types arrive with CLI releases. Rather than model each one and silently drop
 * the rest, the parts every finding shares are lifted out and the remainder is
 * carried through for the UI to render generically.
 */
export type Finding = { 
/**
 * The CLI's `type`, such as `deadlock` or `conflict`.
 */
kind: string, 
/**
 * One sentence describing what was found.
 */
summary: string, 
/**
 * Entities the finding is about; the UI badges their nodes.
 */
entities: Array<string>, 
/**
 * Rules the finding names, where it names any.
 */
rules: Array<string>, 
/**
 * The module this was reported against.
 */
module: string, 
/**
 * The finding's original JSON, for details this struct does not model.
 */
detail: unknown, };
