// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepId } from "./StepId";

/**
 * One picture, once the step it names has been resolved.
 */
export type Frame = { step: StepId, image: string, caption: string | null, passed: boolean, taken_at: string, source: string | null, 
/**
 * The step as it read when this was taken.
 *
 * Stored rather than hashed, and the reason is what a reader is owed when
 * it stops matching: a digest can say *something changed*, and this can
 * show them what the step said then beside what it says now.
 */
said: string, 
/**
 * What this picture is of, beyond which step. See [`Shot::tags`].
 *
 * `default` on both sides, so a manifest sealed before tags existed still
 * reads and a manifest with them is still read by a binary that predates
 * them. Neither is a version change: nothing about what the old fields
 * mean has moved.
 */
tags: { [key in string]: string }, };
