// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verdict } from "./Verdict";

/**
 * The journey this one continues from, and how that one came out.
 *
 * `Ground` rather than anything about standing: `Standing` is already the
 * word for where a *step's* evidence stands, and two of them in one report
 * would be two vocabularies for a reader to keep apart.
 */
export type Ground = { journey: string, 
/**
 * The same name with its words apart, for a heading.
 */
title: string, 
/**
 * How the journey it stands on came out, over all of its steps.
 */
verdict: Verdict, held: number, of: number, };
