// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `/api/health` answers.
 */
export type Health = { 
/**
 * Whether the specification is currently in good order.
 *
 * False for either of two different problems, which the fields below tell
 * apart: the reload itself failed, or it succeeded and the spec it read
 * carries error-severity diagnostics. The second is the common one — a
 * spec that stops parsing mid-edit still produces a document describing
 * what is wrong, so the graph rebuilds fine and is simply reporting an
 * error. Saying `ok` there would be reading the fact that the *tool*
 * worked as a claim about the *spec*.
 */
ok: boolean, 
/**
 * How many times the answer has changed since the server started.
 *
 * The browser polls this and re-fetches when it moves. That is the whole
 * of the live-reload mechanism, and it is a poll rather than a stream
 * deliberately: one request a second to a loopback socket costs nothing,
 * it carries the state of the spec in the same response, and it has no
 * connection to lose, reconnect, or leave half-open behind a laptop lid.
 */
revision: number, allium_version: string, modules: Array<string>, 
/**
 * Why the last reload failed, when it did.
 */
error: string | null, 
/**
 * How many error-severity diagnostics the current spec carries.
 */
errors: number, warnings: number, };
