// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * One `use "./other.allium" as alias` declaration.
 */
export type Import = { 
/**
 * The namespace the importing file uses: the `as` name.
 */
alias: string, 
/**
 * The path as written in the spec.
 */
path: string, 
/**
 * The module this resolved to, when it resolved to one in this set.
 */
target: string | null, span: Span | null, };
