// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line the file's world laid out, and what this journey did with it.
 *
 * The three cases a reader has to be able to tell apart, and the third is the
 * dangerous one: what the journey said, what it inherited, and what it
 * inherited **and then changed**.
 */
export type Inherited = { 
/**
 * The line as the world wrote it: `ada.status = active`.
 */
said: string, 
/**
 * Where in the file it was written.
 */
line: number, 
/**
 * Whether this journey went on to set the same thing itself.
 *
 * Allowed and reported, not forbidden. Eight journeys wanting the same
 * two-member membership and one wanting it `departed` is the ordinary
 * case; forbidding the override splits the file, and allowing it silently
 * is the thing that must not happen.
 */
overridden: boolean, };
