// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { Value } from "./Value";

/**
 * One entity instance: its type, and what its fields hold.
 */
export type Instance = { id: EntityId, 
/**
 * The entity type, unqualified: `Message`.
 */
entity: string, 
/**
 * The module that declares it.
 */
module: string, 
/**
 * Field values, ordered so a world serialises identically twice.
 */
fields: { [key in string]: Value }, };
