// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Truth } from "./Truth";
import type { Unresolved } from "./Unresolved";

/**
 * An invariant, checked against the world a step produced.
 */
export type InvariantVerdict = { id: string, name: string, truth: Truth, 
/**
 * Whether it was already failing before this step ran.
 *
 * The difference between "this rule broke it" and "it was broken when you
 * got here", which a reader needs and the truth value alone cannot give.
 */
already_broken: boolean, unresolved: Array<Unresolved>, };
