// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An invariant: something that must hold after every rule.
 */
export type InvariantDetail = { 
/**
 * The condition as written, absent for a prose-only invariant.
 */
expression: string | null, 
/**
 * Entities the invariant constrains.
 */
entities: Array<string>, };
