// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Walk } from "./Walk";

/**
 * One `.journey` file: what it holds, or why it could not be read.
 */
export type JourneyFile = { 
/**
 * As given on the command line, so a reader can find it on disk.
 */
path: string, 
/**
 * The file's own name, which is what the list shows.
 */
name: string, 
/**
 * Why the file could not be read, if it could not.
 */
error: string | null, 
/**
 * The file as written, for the source strip.
 *
 * A journey is a document somebody wrote, the same as a spec, and the one
 * thing the browser could not do with it was read it. Carried on the
 * report rather than fetched from a second route because it is already
 * being read to parse it, and a journey file is a page rather than a
 * module.
 */
text: string, walks: Array<Walk>, };
