// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JourneyFile } from "./JourneyFile";

/**
 * The whole report, and the one number that summarises it.
 */
export type JourneyReport = { files: Array<JourneyFile>, 
/**
 * How many journeys hold end to end, out of how many were walked.
 */
holding: number, total: number, };
