// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JourneyFile } from "./JourneyFile";
import type { Resolution } from "./Resolution";

/**
 * The whole report, and the one number that summarises it.
 */
export type JourneyReport = { files: Array<JourneyFile>, 
/**
 * How many journeys hold end to end, out of how many were walked.
 */
holding: number, total: number, 
/**
 * Where every step stands: shown, stale, claimed, or nothing.
 *
 * A different question from the verdicts beside it, and the panel keeps
 * them apart on purpose. A verdict says whether the *specification*
 * supports a step; this says whether anybody has shown the software doing
 * it. A step can hold and have never been photographed, and one that has
 * been photographed can still be a step the spec does not support.
 */
evidence: Resolution, };
