// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where in a file a diagnostic points.
 */
export type Location = { 
/**
 * The spec file, as the CLI named it.
 */
file: string, 
/**
 * One-based line.
 */
line: number, 
/**
 * One-based column.
 */
column: number, };
