// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frame } from "./Frame";

/**
 * A sealed run.
 */
export type Manifest = { version: number, 
/**
 * When the seal happened, as the app layer spelled it.
 */
sealed_at: string, 
/**
 * Which walk this was, when the harness names itself.
 */
walk: string | null, frames: Array<Frame>, };
