// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Import } from "./Import";

/**
 * One spec file's identity and its imports.
 */
export type Module = { 
/**
 * The module name: a spec file's stem, `catalogue`.
 */
name: string, 
/**
 * The path it was read from, as given.
 */
path: string, 
/**
 * Its `use` declarations.
 */
imports: Array<Import>, 
/**
 * The language version the file declares, when it declares one.
 */
language_version: number | null, };
