// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeDetail } from "./NodeDetail";
import type { NodeId } from "./NodeId";
import type { NodeKind } from "./NodeKind";
import type { Span } from "./Span";

/**
 * One construct in the spec set.
 */
export type Node = { id: NodeId, kind: NodeKind, 
/**
 * The bare name, as written: `Book`.
 */
name: string, 
/**
 * The module that declares it.
 */
module: string, 
/**
 * How the spec text refers to it across modules: `catalogue/Book`.
 */
qualified: string, 
/**
 * Where it is declared, when the CLI reported a span.
 */
span: Span | null, 
/**
 * Kind-specific payload.
 */
detail: NodeDetail, };
