// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node's address: `module::kind::Name`.
 *
 * Stable across runs and unique across modules, so it can key a selection in a
 * URL, a saved simulation, or a diff between two versions of a spec.
 */
export type NodeId = string;
