// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of construct a node stands for.
 *
 * The vocabulary follows the one the official VS Code extension settled on, so
 * anyone moving between the two tools reads the same words for the same
 * things. [`NodeKind::External`] is the addition: a reference that could not be
 * resolved becomes a visible node rather than a dropped edge.
 */
export type NodeKind = "entity" | "value" | "variant" | "enum" | "rule" | "trigger" | "surface" | "actor" | "config" | "invariant" | "external";
