// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorDetail } from "./ActorDetail";
import type { ConfigDetail } from "./ConfigDetail";
import type { EntityDetail } from "./EntityDetail";
import type { EnumDetail } from "./EnumDetail";
import type { InvariantDetail } from "./InvariantDetail";
import type { RuleDetail } from "./RuleDetail";
import type { SurfaceDetail } from "./SurfaceDetail";
import type { TriggerDetail } from "./TriggerDetail";

/**
 * The kind-specific payload of a node.
 */
export type NodeDetail = { "type": "entity" } & EntityDetail | { "type": "enum" } & EnumDetail | { "type": "config" } & ConfigDetail | { "type": "trigger" } & TriggerDetail | { "type": "rule" } & RuleDetail | { "type": "invariant" } & InvariantDetail | { "type": "surface" } & SurfaceDetail | { "type": "actor" } & ActorDetail | { "type": "none" };
