// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * One test a construct owes, as `allium plan` derives it.
 *
 * Shown against the node it belongs to, so a rule's card can say what would
 * have to be asserted for it to count as covered. The category is kept as the
 * CLI's own string rather than an enum: there are seventeen of them today, they
 * grow with releases, and none of this crate's behaviour branches on which.
 */
export type Obligation = { 
/**
 * The CLI's stable id, such as `rule-success.BorrowCopy`.
 */
id: string, 
/**
 * The CLI's category, such as `rule_success` or `transition_edge`.
 */
category: string, description: string, 
/**
 * What it is owed by: `BorrowCopy`, `Loan.status`.
 */
construct: string, module: string, span: Span | null, };
