// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a name in a journey came from.
 *
 * Worth distinguishing because the three are read differently. A cast member
 * is somebody the journey declared up front; a given is an instance it
 * described in detail; and a catch is a thing that did not exist until a step
 * created it — which is the only one whose absence is a fault rather than a
 * choice.
 */
export type Origin = "cast" | "given" | "caught";
