// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Verdict } from "./Verdict";

/**
 * What became of one line.
 */
export type Outcome = { line: number, verdict: Verdict, 
/**
 * What the line said, as the author wrote it.
 */
about: string, 
/**
 * Why, when there is a why worth reading.
 */
detail: string | null, };
