// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A one-based line and column, as an editor would show it.
 */
export type Position = { line: number, column: number, };
