// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The writing around a construct, as the author left it.
 *
 * A specification is mostly prose. `friend-mesh` has 6,700 lines of Allium and
 * more than half of them are comment: twenty-two of its forty entities open
 * with a paragraph saying why they exist, and a hundred rules carry a
 * `@guidance` block. That writing is where the reasoning lives — a reader who
 * has the fields and not the paragraph above them has the *what* and none of
 * the *why*, which is the half a specification exists to record.
 *
 * The two are kept apart because they are different acts. A comment is a note
 * the author left; `@guidance` is a block the language itself recognises and
 * that the tooling around it reads. Presenting them as one thing would be this
 * tool deciding they are the same.
 */
export type Prose = { 
/**
 * The `--` comment written immediately above the declaration, per line,
 * with the marker stripped. A blank line is an empty string.
 */
note: Array<string>, 
/**
 * The body of each `@guidance` block inside it, per line.
 */
guidance: Array<string>, };
