// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { StepEvidence } from "./StepEvidence";

/**
 * Every step's standing, and the markers that name no step at all.
 */
export type Resolution = { steps: { [key in string]: StepEvidence }, 
/**
 * Markers naming a step no journey has.
 *
 * A rename with half the work done, or a typo. Either way the test still
 * passes while claiming to cover something that does not exist, which is
 * the case worth catching.
 */
unknown: Array<Claim>, };
