// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { Declared } from "./Declared";
import type { StepEvidence } from "./StepEvidence";
import type { Undeclared } from "./Undeclared";

/**
 * Every step's standing, and everything that answers to nothing.
 */
export type Resolution = { steps: { [key in string]: StepEvidence }, 
/**
 * Markers naming a step no journey has.
 *
 * A rename with half the work done, or a typo. Either way the test still
 * passes while claiming to cover something that does not exist, which is
 * the case worth catching.
 */
unknown: Array<Claim>, 
/**
 * The ways each journey says it should be shown, by journey name.
 *
 * Keyed by journey rather than pooled, because the question belongs to the
 * journey that asked it: a set where one journey cares about `platform`
 * should not offer that control on the ones that do not.
 */
axes: { [key in string]: Array<Declared> }, 
/**
 * Tags outside what their journey declared.
 *
 * Empty for a journey that declared nothing — declaring nothing constrains
 * nothing, and a set that has never used this feature must not suddenly
 * report every tag it has. Declaring one axis is opting in to being told
 * about the rest.
 */
undeclared: Array<Undeclared>, };
