// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleClause } from "./RuleClause";
import type { TriggerSource } from "./TriggerSource";

/**
 * A rule: a trigger, preconditions and postconditions.
 */
export type RuleDetail = { 
/**
 * The trigger's name.
 */
trigger: string, source: TriggerSource, clauses: Array<RuleClause>, 
/**
 * Entities the rule creates instances of.
 */
creates: Array<string>, 
/**
 * Triggers the rule emits.
 */
emits: Array<string>, };
