// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClauseVerdict } from "./ClauseVerdict";
import type { Disposition } from "./Disposition";
import type { Effect } from "./Effect";
import type { Unresolved } from "./Unresolved";

/**
 * What one rule did with the trigger.
 */
export type RuleOutcome = { rule: string, name: string, module: string, disposition: Disposition, requires: Array<ClauseVerdict>, effects: Array<Effect>, unresolved: Array<Unresolved>, };
