// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * One `when`, `requires` or `ensures` clause of a rule.
 */
export type RuleClause = { 
/**
 * `when`, `requires` or `ensures`.
 */
keyword: string, 
/**
 * The clause as the spec wrote it.
 */
text: string, span: Span | null, };
