// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A half-open byte range `[start, end)` into a spec file.
 */
export type Span = { start: number, end: number, };
