// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { Edge } from "./Edge";
import type { Finding } from "./Finding";
import type { Module } from "./Module";
import type { Node } from "./Node";
import type { Obligation } from "./Obligation";

/**
 * Every module, construct and relationship in one spec set.
 */
export type SpecGraph = { 
/**
 * The CLI version the documents were produced by.
 */
allium_version: string, modules: Array<Module>, nodes: Array<Node>, edges: Array<Edge>, diagnostics: Array<Diagnostic>, findings: Array<Finding>, obligations: Array<Obligation>, };
