// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How well a step is evidenced.
 */
export type Standing = "shown" | "failing" | "stale" | "claimed" | "unclaimed";
