// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which step of which journey, as a marker and a manifest both spell it.
 *
 * The number rather than the position, and this is the reason the parser
 * insists on one: a step number is a citation, and a citation that moves when
 * somebody inserts a step above it quietly starts pointing elsewhere. A
 * photograph filed under a position would be re-filed by an edit that did not
 * touch it.
 */
export type StepId = string;
