// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Enabled } from "./Enabled";
import type { Event } from "./Event";
import type { InvariantVerdict } from "./InvariantVerdict";
import type { RuleOutcome } from "./RuleOutcome";
import type { World } from "./World";

/**
 * Everything one step produced.
 */
export type StepOutcome = { world: World, event: Event, 
/**
 * Every rule that waits for this trigger, in id order.
 */
rules: Array<RuleOutcome>, invariants: Array<InvariantVerdict>, 
/**
 * State-condition rules that hold after the step and did not before.
 */
newly_enabled: Array<Enabled>, 
/**
 * Triggers the applied rules emitted, for the user to fire next.
 */
emitted: Array<string>, };
