// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { Frame } from "./Frame";
import type { Standing } from "./Standing";

/**
 * One step, and everything anybody has said about it.
 */
export type StepEvidence = { standing: Standing, 
/**
 * The pictures of this step, in the order the run took them.
 */
frames: Array<Frame>, 
/**
 * Where the code says it demonstrates this.
 */
claims: Array<Claim>, 
/**
 * What the step says now, when a frame disagrees with it.
 *
 * Only carried when something is stale, because that is the only time a
 * reader needs both halves in front of them.
 */
says_now: string | null, };
