// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something a journey was told rather than shown, and by whom.
 */
export type Stipulation = { 
/**
 * The fact, as the journey put it: `ada.is_at_limit = false`.
 */
said: string, 
/**
 * The journey that said it, when it was not this one.
 *
 * A chain carries its stipulations forward. Without this a reader has no
 * way to tell what *this* journey was told from what it walked in on, and
 * the rule that nothing passes invisibly would hold for one journey and
 * not for two.
 */
through: string | null, };
