// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceOperation } from "./SurfaceOperation";

/**
 * A surface: what an actor can see and do at a boundary.
 */
export type SurfaceDetail = { 
/**
 * The actor or entity type on the other side.
 */
actor: string | null, 
/**
 * The binding name the surface gave that actor.
 */
actor_binding: string | null, 
/**
 * The entity the surface is scoped to.
 */
context: string | null, 
/**
 * Fields visible across the boundary, as written.
 */
exposes: Array<string>, provides: Array<SurfaceOperation>, 
/**
 * Named `@guarantee` constraints, which are prose.
 */
guarantees: Array<string>, };
