// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One operation a surface offers.
 */
export type SurfaceOperation = { 
/**
 * The trigger it fires.
 */
trigger: string, parameters: Array<string>, 
/**
 * The guard that decides whether it is offered.
 */
when: string | null, };
