// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `from -> to` step in a lifecycle.
 */
export type TransitionEdge = { from: string, to: string, };
