// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransitionEdge } from "./TransitionEdge";

/**
 * An entity's declared lifecycle for one status field.
 */
export type TransitionGraph = { 
/**
 * The field the lifecycle governs, usually `status`.
 */
field: string, states: Array<string>, edges: Array<TransitionEdge>, 
/**
 * States from which nothing further may happen.
 */
terminal: Array<string>, };
