// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriggerSource } from "./TriggerSource";

/**
 * A trigger: what a rule waits for.
 */
export type TriggerDetail = { source: TriggerSource, 
/**
 * Parameter names, for an external stimulus.
 */
parameters: Array<string>, 
/**
 * The condition as written, for a state or temporal trigger.
 */
condition: string | null, 
/**
 * The entity a state condition is bound over.
 */
entity: string | null, };
