// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What makes a trigger happen.
 *
 * The distinction the simulator is built on. An external stimulus is something
 * a person or another system does, so the user fires it. A state condition is
 * something that *becomes* true, so the simulator offers it as a next step once
 * a change makes it hold — and walking that chain is as close to a user journey
 * as a spec without journeys can get.
 */
export type TriggerSource = "external" | "state" | "temporal";
