// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether something holds, does not hold, or could not be decided.
 */
export type Truth = "true" | "false" | "unknown";
