// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepId } from "./StepId";

/**
 * A tag outside what its journey declared.
 */
export type Undeclared = { step: StepId, image: string, key: string, value: string, 
/**
 * Whether the *key* is unknown, rather than the value on a known key.
 *
 * Read differently: an unknown key is usually a typo for a declared one,
 * and an unknown value is usually a way of showing the journey that
 * somebody added without saying so.
 */
key_undeclared: boolean, };
