// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * A sub-expression the evaluator could not decide, and why.
 */
export type Unresolved = { 
/**
 * What could not be decided, in the reader's terms.
 */
reason: string, 
/**
 * The sub-expression, as the spec wrote it, when a span located it.
 */
expression: string | null, span: Span | null, };
