// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a line came out — statically, or once it was walked.
 *
 * The three a simulator gives, and the two a journey needs and a simulation
 * does not. `Unspecified` is a requirement nobody has met yet, which is the
 * ordinary state of a journey written before the spec it demands; `Unexposed`
 * is a system that does the right thing and tells nobody.
 */
export type Verdict = "specified" | "undecided" | "refused" | "unspecified" | "unexposed" | "remark";
