// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastMember } from "./CastMember";
import type { Outcome } from "./Outcome";
import type { Walked } from "./Walked";

/**
 * What became of a journey.
 */
export type Walk = { name: string, 
/**
 * Everybody the journey named, in the order the names were bound.
 */
cast: Array<CastMember>, 
/**
 * What the journey said it was for, and how it said it ends.
 *
 * Carried on the report rather than left in the source, because the whole
 * question a reader has is whether the spec delivers *this* — and a list
 * of verdicts with the intent stripped off cannot be read against it.
 */
goal: Array<string>, ends: Array<string>, 
/**
 * Where the journey starts in its file, for going there.
 */
line: number, steps: Array<Walked>, 
/**
 * What the journey was told rather than shown, always reported.
 */
stipulated: Array<string>, 
/**
 * What was wrong with the journey outside its steps.
 *
 * Counted in the verdict, because the flagship case of this whole design
 * is a requirement nobody has met — and a cast naming a type the spec
 * does not have is exactly that, one line before the steps begin.
 */
notes: Array<Outcome>, };
