// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Outcome } from "./Outcome";
import type { World } from "./World";

/**
 * What became of one step.
 */
export type Walked = { number: number, title: string, outcomes: Array<Outcome>, 
/**
 * The world as it stood when this step finished.
 *
 * Kept per step rather than only at the end, because the question a
 * journey raises about a value is *when* it became that — and a single
 * final state answers "what is Ada's loan now" while hiding the step that
 * made it so.
 */
world: World, };
