// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CastMember } from "./CastMember";
import type { Ground } from "./Ground";
import type { Inherited } from "./Inherited";
import type { Outcome } from "./Outcome";
import type { Stipulation } from "./Stipulation";
import type { Walked } from "./Walked";

/**
 * What became of a journey.
 */
export type Walk = { 
/**
 * The journey's name, which is its identity: an evidence marker says
 * `journey: <name>.3`, and the panel finds a walk by it.
 */
name: string, 
/**
 * The same name with its words apart, for a heading.
 *
 * Derived rather than declared. A journey already says what it is for in
 * `goal:`, in the author's own words; a second place to write the same
 * thing differently is a second place for them to disagree.
 */
title: string, 
/**
 * Everybody the journey named, in the order the names were bound.
 */
cast: Array<CastMember>, 
/**
 * What the journey said it was for, and how it said it ends.
 *
 * Carried on the report rather than left in the source, because the whole
 * question a reader has is whether the spec delivers *this* — and a list
 * of verdicts with the intent stripped off cannot be read against it.
 */
goal: Array<string>, ends: Array<string>, 
/**
 * Where the journey starts in its file, for going there.
 */
line: number, steps: Array<Walked>, 
/**
 * What the journey was told rather than shown, always reported.
 *
 * Including everything the journeys it stands on were told, because an
 * agent that could make this one pass by stipulating in the one before it
 * would have found the loophole this rule exists to close.
 */
stipulated: Array<Stipulation>, 
/**
 * The journey this one continues from, and how that one came out.
 *
 * A world is a list of lines and is reported line by line; the end state
 * of another journey is a world and cannot be. What can be said is that
 * the ground under this is itself checked, and what its verdict was —
 * which is stronger than a list, and is why [`Walk::verdict`] can never
 * come out better than this.
 */
after: Ground | null, 
/**
 * Every line the file's `world` laid out, and what became of it.
 *
 * Empty unless the journey inherits one, because otherwise this would
 * print a journey's own `given` block back at it and say nothing. When it
 * does inherit, this is the whole of what makes that safe: a step holding
 * because of a line somewhere else in the file is passing invisibly, and
 * this is where it stops being invisible.
 */
inherited: Array<Inherited>, 
/**
 * What was wrong with the journey outside its steps.
 *
 * Counted in the verdict, because the flagship case of this whole design
 * is a requirement nobody has met — and a cast naming a type the spec
 * does not have is exactly that, one line before the steps begin.
 */
notes: Array<Outcome>, };
