// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Walked } from "./Walked";

/**
 * What became of a journey.
 */
export type Walk = { name: string, 
/**
 * What the journey said it was for, and how it said it ends.
 *
 * Carried on the report rather than left in the source, because the whole
 * question a reader has is whether the spec delivers *this* — and a list
 * of verdicts with the intent stripped off cannot be read against it.
 */
goal: Array<string>, ends: Array<string>, 
/**
 * Where the journey starts in its file, for going there.
 */
line: number, steps: Array<Walked>, 
/**
 * What the journey was told rather than shown, always reported.
 */
stipulated: Array<string>, };
