// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Answer } from "./Answer";
import type { EntityId } from "./EntityId";
import type { Instance } from "./Instance";
import type { Value } from "./Value";

/**
 * Every instance, the configuration, and the time.
 */
export type World = { 
/**
 * Instances by id, ordered so the world serialises identically twice.
 */
entities: { [key in EntityId]: Instance }, 
/**
 * Configuration in force, keyed `module.parameter`.
 */
config: { [key in string]: Value }, 
/**
 * What a journey answered on the specification's behalf.
 *
 * A specification names functions it never defines — `may_invite(group,
 * issuer)`, whose policy has not been decided — and no simulator can work
 * one out. Somebody has to say, and what they said is state: it belongs
 * beside the config, which is the other thing here that came from outside
 * the world rather than from anything that happened in it.
 */
answers: Array<Answer>, 
/**
 * The current time, in milliseconds. Advanced only by the user.
 *
 * `number` on the wire; see the note on [`Value::Int`].
 */
now: number, 
/**
 * The next ordinal for each entity type, so ids never repeat.
 *
 * Carried in the world rather than derived from what exists, so that
 * removing an instance does not make the next creation reuse its id — two
 * different things in one trace must never share a name.
 */
next_ordinal: Record<string, number>, };
